### ISSUE TITLE
fastg file - gfa

### ISSUE THREAD

**Issue by valc30** [dpellow/SCAPP#2]
Hi, 
I used SPAdes for my assembly and I would like to try SCAPP but the only assembly graph that was built by SPAdes was a gfa file. I don't find any tool for the conversion. Would the metaflye_gfa2fastg.py work for short reads? 

Thanks!

**Comment by dpellow** [comment]
I don't see that there were any changes in SPAdes so I believe it should output a fastg file. The best option is to first see if you can locate it. Can you list the contents of the spades output directory and the end of the spades log file? If you don't see the fastg can you try to run spades --test and post the contents of the test output directory and end of the test log file?
If that doesn't work out I can try to see about converting the gfa to fastg. It really depends on the specific gfa implementation used.

**Comment by valc30** [comment]
Solved, found it, thanks!

**Comment by dpellow** [comment]
Great
